// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6-HgUhcfIvIVxHLUWVrUqOeHOt3I9Mto',
    appId: '1:753276740560:web:4e3c3e6529ea2dffe60fd5',
    messagingSenderId: '753276740560',
    projectId: 'imagetotext-d3125',
    authDomain: 'imagetotext-d3125.firebaseapp.com',
    storageBucket: 'imagetotext-d3125.firebasestorage.app',
    measurementId: 'G-PT1X4XCMF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRQwhDxAgOHSOuGK5W8ATbJGYQ2WRiAh4',
    appId: '1:753276740560:android:dc3ba520ef3e1b91e60fd5',
    messagingSenderId: '753276740560',
    projectId: 'imagetotext-d3125',
    storageBucket: 'imagetotext-d3125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA5nNEaI6Jkrl9JAZUGTdRL-YklRtx-E0',
    appId: '1:753276740560:ios:aae8a5c1172f4fd8e60fd5',
    messagingSenderId: '753276740560',
    projectId: 'imagetotext-d3125',
    storageBucket: 'imagetotext-d3125.firebasestorage.app',
    iosBundleId: 'com.example.ocrScannerDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA5nNEaI6Jkrl9JAZUGTdRL-YklRtx-E0',
    appId: '1:753276740560:ios:aae8a5c1172f4fd8e60fd5',
    messagingSenderId: '753276740560',
    projectId: 'imagetotext-d3125',
    storageBucket: 'imagetotext-d3125.firebasestorage.app',
    iosBundleId: 'com.example.ocrScannerDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6-HgUhcfIvIVxHLUWVrUqOeHOt3I9Mto',
    appId: '1:753276740560:web:3d66572144453128e60fd5',
    messagingSenderId: '753276740560',
    projectId: 'imagetotext-d3125',
    authDomain: 'imagetotext-d3125.firebaseapp.com',
    storageBucket: 'imagetotext-d3125.firebasestorage.app',
    measurementId: 'G-D843H65MEM',
  );
}
